language: groovy
jdk:
- openjdk7
before_script:
- rm -rf target
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: A3ihU89XVCKFObuV62XYZV5mY1Ifu1zMZG+owY7dHQnA8D27lRpZHRAE3ya8tryt9lc+ndbSPQUfMP8hKUA77BXPTE2uAraM2xoRnuWEIe3jokVsCtzLj04Vo190ap751DWoHIZEp2+797jNpqaMh/DpjNCPhwNH3mptB1ofFPs=
  - secure: H2/dB3jqixDfg0yBzctC195q+rVLkdW/dURb+Zwf0GXmEejZUczBclz2TTnl/8lFjgMITWrKvrJ9DH9xTxk3LPN2eESE/h6dkfNOn9xNpGkBmGjlfSgO/jpvVh2ZlQjkF8knmPEpSE/t1DKZ31xcVTVP7FS8YXM4VAcoYfmel14=
  - secure: WxyohkKRngaIbbUgHYLKswX99eqRdhC4oaW6zWuzIBddlYaQkCz0cuCvnTemiwuAIvKLn1yygmL1EqcFQIx5s+6bCwGHUeoPiJeC23YNJPeQc8Rfl4GW+ofNCucZ+7oKK7LOOuPz1zZBn+hCfBo7lVIsMsw9KyUpwjWcRfOGH3Q=
  - secure: Yf4sBMGEhpMCu3pjqmOlT8QaGX8O4HY7xkbh+AZap7xUgM1zTVtOqH1oRhWGTSIgF/VU8xvx+DMpiRuNCXnPdrCP5Kz9gdo3LM0GejsTXcVfau/A2/nLCKc7Xp5+1/KDjTfvB+8eRzYuezlmYmmiyseL8KZgqKzTP+H41oonnWk=
  - secure: RxkT3DmVvI0kHT9ZUxOVbLgpdNqnWqnwhPiYQgSzp+qM8r5WO955FXoldmj8b2jB3V7OVsh2Tk92b8BXWeSP4yKpuFhx4IjpNsQUjz7ATrteg+yUph5TJb5yW826rC4bA7jfeO9THGJYOnYhy0fWxixalhK9s0Ge6/ufpLGuwT4=
deploy:
  provider: releases
  api_key:
    secure: m7e4FuggqcA7DnyBCpPnrO4UZ1fDU0Eg9KlN2r0yifRfdxMdOcNNFfDdaEiJAuXJTjxoaBCgXQu3ALHHLkSeaAACkHDPxwmbba3KRYS757Z7jjYU8DLprj7m1iWecVu5Iccl1i2RUZcjZU4uVgnFC4UFuXZ/e9yM8/qLATshA8Y=
  file: build/libs/geb-${TRAVIS_TAG:1}.jar
  on:
    repo: grails3-plugins/geb
